//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoVenta.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        private decimal precioCompraField;
        
        private decimal precioVentaField;
        
        private int inventarioField;
        
        private System.DateTime fechaCreacionField;
        
        private bool esActivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal precioCompra {
            get {
                return this.precioCompraField;
            }
            set {
                if ((this.precioCompraField.Equals(value) != true)) {
                    this.precioCompraField = value;
                    this.RaisePropertyChanged("precioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal precioVenta {
            get {
                return this.precioVentaField;
            }
            set {
                if ((this.precioVentaField.Equals(value) != true)) {
                    this.precioVentaField = value;
                    this.RaisePropertyChanged("precioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int inventario {
            get {
                return this.inventarioField;
            }
            set {
                if ((this.inventarioField.Equals(value) != true)) {
                    this.inventarioField = value;
                    this.RaisePropertyChanged("inventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                if ((this.fechaCreacionField.Equals(value) != true)) {
                    this.fechaCreacionField = value;
                    this.RaisePropertyChanged("fechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool esActivo {
            get {
                return this.esActivoField;
            }
            set {
                if ((this.esActivoField.Equals(value) != true)) {
                    this.esActivoField = value;
                    this.RaisePropertyChanged("esActivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        PuntoVenta.ServiceReference1.HelloWorldResponse HelloWorld(PuntoVenta.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.HelloWorldResponse> HelloWorldAsync(PuntoVenta.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ListAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAllProducts", ReplyAction="*")]
        PuntoVenta.ServiceReference1.ListAllProductsResponse ListAllProducts(PuntoVenta.ServiceReference1.ListAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.ListAllProductsResponse> ListAllProductsAsync(PuntoVenta.ServiceReference1.ListAllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        PuntoVenta.ServiceReference1.GetProductByIdResponse GetProductById(PuntoVenta.ServiceReference1.GetProductByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.GetProductByIdResponse> GetProductByIdAsync(PuntoVenta.ServiceReference1.GetProductByIdRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveNewProduct", ReplyAction="*")]
        PuntoVenta.ServiceReference1.SaveNewProductResponse SaveNewProduct(PuntoVenta.ServiceReference1.SaveNewProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveNewProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.SaveNewProductResponse> SaveNewProductAsync(PuntoVenta.ServiceReference1.SaveNewProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PuntoVenta.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PuntoVenta.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.ListAllProductsRequestBody Body;
        
        public ListAllProductsRequest() {
        }
        
        public ListAllProductsRequest(PuntoVenta.ServiceReference1.ListAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllProductsRequestBody {
        
        public ListAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.ListAllProductsResponseBody Body;
        
        public ListAllProductsResponse() {
        }
        
        public ListAllProductsResponse(PuntoVenta.ServiceReference1.ListAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.ServiceReference1.Producto[] ListAllProductsResult;
        
        public ListAllProductsResponseBody() {
        }
        
        public ListAllProductsResponseBody(PuntoVenta.ServiceReference1.Producto[] ListAllProductsResult) {
            this.ListAllProductsResult = ListAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductById", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.GetProductByIdRequestBody Body;
        
        public GetProductByIdRequest() {
        }
        
        public GetProductByIdRequest(PuntoVenta.ServiceReference1.GetProductByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public GetProductByIdRequestBody() {
        }
        
        public GetProductByIdRequestBody(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.GetProductByIdResponseBody Body;
        
        public GetProductByIdResponse() {
        }
        
        public GetProductByIdResponse(PuntoVenta.ServiceReference1.GetProductByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.ServiceReference1.Producto GetProductByIdResult;
        
        public GetProductByIdResponseBody() {
        }
        
        public GetProductByIdResponseBody(PuntoVenta.ServiceReference1.Producto GetProductByIdResult) {
            this.GetProductByIdResult = GetProductByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveNewProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveNewProduct", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.SaveNewProductRequestBody Body;
        
        public SaveNewProductRequest() {
        }
        
        public SaveNewProductRequest(PuntoVenta.ServiceReference1.SaveNewProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveNewProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal precioCompra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal precioVenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int inventario;
        
        public SaveNewProductRequestBody() {
        }
        
        public SaveNewProductRequestBody(int idProducto, string nombre, string descripcion, decimal precioCompra, decimal precioVenta, int inventario) {
            this.idProducto = idProducto;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.precioCompra = precioCompra;
            this.precioVenta = precioVenta;
            this.inventario = inventario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveNewProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveNewProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntoVenta.ServiceReference1.SaveNewProductResponseBody Body;
        
        public SaveNewProductResponse() {
        }
        
        public SaveNewProductResponse(PuntoVenta.ServiceReference1.SaveNewProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveNewProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PuntoVenta.ServiceReference1.Producto SaveNewProductResult;
        
        public SaveNewProductResponseBody() {
        }
        
        public SaveNewProductResponseBody(PuntoVenta.ServiceReference1.Producto SaveNewProductResult) {
            this.SaveNewProductResult = SaveNewProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : PuntoVenta.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<PuntoVenta.ServiceReference1.WebServiceSoap>, PuntoVenta.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.ServiceReference1.HelloWorldResponse PuntoVenta.ServiceReference1.WebServiceSoap.HelloWorld(PuntoVenta.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string nombre) {
            PuntoVenta.ServiceReference1.HelloWorldRequest inValue = new PuntoVenta.ServiceReference1.HelloWorldRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.nombre = nombre;
            PuntoVenta.ServiceReference1.HelloWorldResponse retVal = ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.HelloWorldResponse> PuntoVenta.ServiceReference1.WebServiceSoap.HelloWorldAsync(PuntoVenta.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string nombre) {
            PuntoVenta.ServiceReference1.HelloWorldRequest inValue = new PuntoVenta.ServiceReference1.HelloWorldRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.nombre = nombre;
            return ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.ServiceReference1.ListAllProductsResponse PuntoVenta.ServiceReference1.WebServiceSoap.ListAllProducts(PuntoVenta.ServiceReference1.ListAllProductsRequest request) {
            return base.Channel.ListAllProducts(request);
        }
        
        public PuntoVenta.ServiceReference1.Producto[] ListAllProducts() {
            PuntoVenta.ServiceReference1.ListAllProductsRequest inValue = new PuntoVenta.ServiceReference1.ListAllProductsRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.ListAllProductsRequestBody();
            PuntoVenta.ServiceReference1.ListAllProductsResponse retVal = ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).ListAllProducts(inValue);
            return retVal.Body.ListAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.ListAllProductsResponse> PuntoVenta.ServiceReference1.WebServiceSoap.ListAllProductsAsync(PuntoVenta.ServiceReference1.ListAllProductsRequest request) {
            return base.Channel.ListAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.ListAllProductsResponse> ListAllProductsAsync() {
            PuntoVenta.ServiceReference1.ListAllProductsRequest inValue = new PuntoVenta.ServiceReference1.ListAllProductsRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.ListAllProductsRequestBody();
            return ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).ListAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.ServiceReference1.GetProductByIdResponse PuntoVenta.ServiceReference1.WebServiceSoap.GetProductById(PuntoVenta.ServiceReference1.GetProductByIdRequest request) {
            return base.Channel.GetProductById(request);
        }
        
        public PuntoVenta.ServiceReference1.Producto GetProductById(int idProducto) {
            PuntoVenta.ServiceReference1.GetProductByIdRequest inValue = new PuntoVenta.ServiceReference1.GetProductByIdRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.GetProductByIdRequestBody();
            inValue.Body.idProducto = idProducto;
            PuntoVenta.ServiceReference1.GetProductByIdResponse retVal = ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).GetProductById(inValue);
            return retVal.Body.GetProductByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.GetProductByIdResponse> PuntoVenta.ServiceReference1.WebServiceSoap.GetProductByIdAsync(PuntoVenta.ServiceReference1.GetProductByIdRequest request) {
            return base.Channel.GetProductByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.GetProductByIdResponse> GetProductByIdAsync(int idProducto) {
            PuntoVenta.ServiceReference1.GetProductByIdRequest inValue = new PuntoVenta.ServiceReference1.GetProductByIdRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.GetProductByIdRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).GetProductByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntoVenta.ServiceReference1.SaveNewProductResponse PuntoVenta.ServiceReference1.WebServiceSoap.SaveNewProduct(PuntoVenta.ServiceReference1.SaveNewProductRequest request) {
            return base.Channel.SaveNewProduct(request);
        }
        
        public PuntoVenta.ServiceReference1.Producto SaveNewProduct(int idProducto, string nombre, string descripcion, decimal precioCompra, decimal precioVenta, int inventario) {
            PuntoVenta.ServiceReference1.SaveNewProductRequest inValue = new PuntoVenta.ServiceReference1.SaveNewProductRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.SaveNewProductRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.precioCompra = precioCompra;
            inValue.Body.precioVenta = precioVenta;
            inValue.Body.inventario = inventario;
            PuntoVenta.ServiceReference1.SaveNewProductResponse retVal = ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).SaveNewProduct(inValue);
            return retVal.Body.SaveNewProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.SaveNewProductResponse> PuntoVenta.ServiceReference1.WebServiceSoap.SaveNewProductAsync(PuntoVenta.ServiceReference1.SaveNewProductRequest request) {
            return base.Channel.SaveNewProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntoVenta.ServiceReference1.SaveNewProductResponse> SaveNewProductAsync(int idProducto, string nombre, string descripcion, decimal precioCompra, decimal precioVenta, int inventario) {
            PuntoVenta.ServiceReference1.SaveNewProductRequest inValue = new PuntoVenta.ServiceReference1.SaveNewProductRequest();
            inValue.Body = new PuntoVenta.ServiceReference1.SaveNewProductRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.precioCompra = precioCompra;
            inValue.Body.precioVenta = precioVenta;
            inValue.Body.inventario = inventario;
            return ((PuntoVenta.ServiceReference1.WebServiceSoap)(this)).SaveNewProductAsync(inValue);
        }
    }
}
